// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Patitas.Data;

namespace Patitas.Migrations
{
    [DbContext(typeof(MascotaContext))]
    [Migration("20190612091706_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Patitas.Models.Adopcion", b =>
                {
                    b.Property<int>("IdAdoptante")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DNI");

                    b.Property<string>("Direccion");

                    b.Property<DateTime>("FechaAdop");

                    b.Property<int>("IdUser");

                    b.HasKey("IdAdoptante");

                    b.HasIndex("IdUser");

                    b.ToTable("Adopciones");
                });

            modelBuilder.Entity("Patitas.Models.Anuncio", b =>
                {
                    b.Property<int>("IdAnuncio")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contenido");

                    b.Property<DateTime>("FechaFin");

                    b.Property<DateTime>("FechaInicio");

                    b.HasKey("IdAnuncio");

                    b.ToTable("Anuncios");
                });

            modelBuilder.Entity("Patitas.Models.FotosMascota", b =>
                {
                    b.Property<int>("IdFotoMascota")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IdMascota");

                    b.Property<int>("MyProperty");

                    b.Property<string>("nombre");

                    b.HasKey("IdFotoMascota");

                    b.HasIndex("IdMascota");

                    b.ToTable("FotosMascotas");
                });

            modelBuilder.Entity("Patitas.Models.ListaEspera", b =>
                {
                    b.Property<int>("IdListaEspera")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellidos");

                    b.Property<string>("Nombre");

                    b.Property<string>("SexoMascota");

                    b.Property<string>("Tamanio");

                    b.Property<string>("TipoMascota");

                    b.HasKey("IdListaEspera");

                    b.ToTable("ListaDeEspera");
                });

            modelBuilder.Entity("Patitas.Models.Mascota", b =>
                {
                    b.Property<int>("IdMascota")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<int>("Edad");

                    b.Property<string>("Estado");

                    b.Property<DateTime>("FechaRegistro");

                    b.Property<int>("IdRefugio");

                    b.Property<int>("IdTipoMascota");

                    b.Property<int>("IdUser");

                    b.Property<string>("Nombre");

                    b.Property<string>("Personalidades");

                    b.Property<string>("PuedeEstarSolo");

                    b.Property<string>("Sexo");

                    b.Property<string>("Tamaño");

                    b.Property<string>("Ubicacion");

                    b.HasKey("IdMascota");

                    b.HasIndex("IdRefugio");

                    b.HasIndex("IdTipoMascota");

                    b.HasIndex("IdUser");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("Patitas.Models.Mensaje", b =>
                {
                    b.Property<int>("IdMensaje")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Asunto");

                    b.Property<string>("Contenido");

                    b.Property<string>("Email");

                    b.Property<DateTime>("Fecha");

                    b.Property<bool>("IsRead");

                    b.Property<string>("Nombre");

                    b.HasKey("IdMensaje");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("Patitas.Models.Pregunta", b =>
                {
                    b.Property<int>("IdPregunta")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contenido");

                    b.Property<DateTime>("Fecha");

                    b.Property<int>("IdMascota");

                    b.Property<int>("IdUser");

                    b.HasKey("IdPregunta");

                    b.HasIndex("IdMascota");

                    b.HasIndex("IdUser");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("Patitas.Models.Refugio", b =>
                {
                    b.Property<int>("IdRefugio")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<DateTime>("FechaDeCreacion");

                    b.Property<int>("IdUser");

                    b.Property<string>("Logo");

                    b.Property<string>("Nombre");

                    b.Property<int>("Telefono");

                    b.Property<string>("Ubicacion");

                    b.HasKey("IdRefugio");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("Refugios");
                });

            modelBuilder.Entity("Patitas.Models.TipoMascota", b =>
                {
                    b.Property<int>("IdTipoMascota")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<string>("Nombre");

                    b.HasKey("IdTipoMascota");

                    b.ToTable("TipoMascotas");
                });

            modelBuilder.Entity("Patitas.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellidos");

                    b.Property<string>("Email");

                    b.Property<DateTime>("FechaDeRegistro");

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("Nombre");

                    b.Property<string>("Password");

                    b.Property<string>("PasswordConfirm");

                    b.Property<string>("Sexo");

                    b.Property<string>("token_recovery");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Patitas.Models.Veterinaria", b =>
                {
                    b.Property<int>("IdVeterinaria")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Direccion");

                    b.Property<string>("Logo");

                    b.Property<string>("Nombre");

                    b.Property<string>("Responsable");

                    b.Property<int>("Telefono");

                    b.HasKey("IdVeterinaria");

                    b.ToTable("Veterinarias");
                });

            modelBuilder.Entity("Patitas.Models.Adopcion", b =>
                {
                    b.HasOne("Patitas.Models.User")
                        .WithMany("Adopcion")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Patitas.Models.FotosMascota", b =>
                {
                    b.HasOne("Patitas.Models.Mascota")
                        .WithMany("FotosMascota")
                        .HasForeignKey("IdMascota")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Patitas.Models.Mascota", b =>
                {
                    b.HasOne("Patitas.Models.Refugio")
                        .WithMany("Mascota")
                        .HasForeignKey("IdRefugio")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Patitas.Models.TipoMascota")
                        .WithMany("Mascota")
                        .HasForeignKey("IdTipoMascota")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Patitas.Models.User")
                        .WithMany("Mascota")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Patitas.Models.Pregunta", b =>
                {
                    b.HasOne("Patitas.Models.Mascota")
                        .WithMany("Pregunta")
                        .HasForeignKey("IdMascota")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Patitas.Models.User")
                        .WithMany("Pregunta")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Patitas.Models.Refugio", b =>
                {
                    b.HasOne("Patitas.Models.User")
                        .WithOne("Refugio")
                        .HasForeignKey("Patitas.Models.Refugio", "IdUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
